spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:ssl/spring_ssl.pfx
    key-store-password: root